name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t your-docker-hub-username/nginx-static-website:latest .
          docker tag your-docker-hub-username/nginx-static-website:latest your-docker-hub-username/nginx-static-website:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-docker-hub-username/nginx-static-website:latest
          docker push your-docker-hub-username/nginx-static-website:${{ github.sha }}
